import asyncio
import logging
from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from app.api.schemas import (
    HealthResponse,
    IngestRequest,
    IngestResponse,
    QueryRequest,
    QueryResponse,
)
from app.core.config import get_settings
from app.core.dependencies import get_rag_service
from app.core.limiter import limiter
from app.services.rag_service import RagService

logger = logging.getLogger(__name__)
settings = get_settings()
router = APIRouter(tags=["RAG"])


@router.get("/health", response_model=HealthResponse, summary="Health Check")
async def health_check() -> HealthResponse:
    """Return health status of the API."""
    return HealthResponse()


@router.post("/ingest", response_model=IngestResponse, summary="Ingest Excel Knowledge Base")
@limiter.limit(settings.RATE_LIMIT_INGEST)
async def ingest_knowledge_base(
    request: Request,
    body: IngestRequest = IngestRequest(),
    rag_service: RagService = Depends(get_rag_service),
) -> IngestResponse:
    """Read the Excel knowledge base, create vector embeddings, and store them into ChromaDB."""
    try:
        result = await asyncio.to_thread(
            rag_service.ingest_documents,
            file_path=body.file_path,
            reset_collection=body.reset_collection,
        )
        return IngestResponse(**result)
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )
    except Exception as e:
        logger.error(f"Ingestion failed: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ingestion failed: {str(e)}",
        )


@router.post("/ask", response_model=QueryResponse, summary="Ask question using RAG")
@limiter.limit(settings.RATE_LIMIT_QUERY)
async def ask_question(
    request: Request,
    body: QueryRequest,
    rag_service: RagService = Depends(get_rag_service),
) -> QueryResponse:
    """Query the RAG pipeline to retrieve relevant documents and generate an answer via Ollama LLM."""
    try:
        result = await asyncio.wait_for(
            asyncio.to_thread(rag_service.query, question=body.query, top_k=body.top_k),
            timeout=settings.REQUEST_TIMEOUT_SECONDS,
        )
        return QueryResponse(**result)
    except asyncio.TimeoutError:
        logger.error(f"Query timed out after {settings.REQUEST_TIMEOUT_SECONDS}s")
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail=f"Query timed out after {settings.REQUEST_TIMEOUT_SECONDS} seconds.",
        )
    except Exception as e:
        logger.error(f"Query execution failed: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Query execution failed: {str(e)}",
        )


@router.post("/ask/stream", summary="Ask question with token streaming")
@limiter.limit(settings.RATE_LIMIT_QUERY)
async def ask_question_stream(
    request: Request,
    body: QueryRequest,
    rag_service: RagService = Depends(get_rag_service),
):
    """Stream response tokens in real-time as they are generated by the LLM."""
    async def timed_stream():
        try:
            async for token in rag_service.query_stream(question=body.query, top_k=body.top_k):
                yield token
        except asyncio.TimeoutError:
            logger.error(f"Streaming query timed out after {settings.REQUEST_TIMEOUT_SECONDS}s")
            yield "\n[Error: Stream timed out while generating response]"
        except Exception as e:
            logger.error(f"Stream error: {e}", exc_info=True)
            yield f"\n[Error: {str(e)}]"

    try:
        return StreamingResponse(
            timed_stream(),
            media_type="text/event-stream",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Stream execution failed: {str(e)}",
        )
