from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from app.api.schemas import (
    HealthResponse,
    IngestRequest,
    IngestResponse,
    QueryRequest,
    QueryResponse,
)
from app.core.dependencies import get_rag_service
from app.services.rag_service import RagService

router = APIRouter(tags=["RAG"])


@router.get("/health", response_model=HealthResponse, summary="Health Check")
async def health_check() -> HealthResponse:
    """Return health status of the API."""
    return HealthResponse()


@router.post("/ingest", response_model=IngestResponse, summary="Ingest Excel Knowledge Base")
async def ingest_knowledge_base(
    request: IngestRequest = IngestRequest(),
    rag_service: RagService = Depends(get_rag_service),
) -> IngestResponse:
    """Read the Excel knowledge base, create vector embeddings, and store them into ChromaDB."""
    try:
        result = rag_service.ingest_documents(
            file_path=request.file_path,
            reset_collection=request.reset_collection,
        )
        return IngestResponse(**result)
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ingestion failed: {str(e)}",
        )


@router.post("/ask", response_model=QueryResponse, summary="Ask question using RAG")
async def ask_question(
    request: QueryRequest,
    rag_service: RagService = Depends(get_rag_service),
) -> QueryResponse:
    """Query the RAG pipeline to retrieve relevant documents and generate an answer via Ollama LLM."""
    try:
        result = rag_service.query(question=request.query, top_k=request.top_k)
        return QueryResponse(**result)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Query execution failed: {str(e)}",
        )


@router.post("/ask/stream", summary="Ask question with token streaming")
async def ask_question_stream(
    request: QueryRequest,
    rag_service: RagService = Depends(get_rag_service),
):
    """Stream response tokens in real-time as they are generated by the LLM."""
    try:
        return StreamingResponse(
            rag_service.query_stream(question=request.query, top_k=request.top_k),
            media_type="text/event-stream",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Stream execution failed: {str(e)}",
        )
